nodeLinker: node-modules

packageExtensions:
  # deasync didn't add node-gyp as a direct dependency so it fails to build in
  # Yarn (https://github.com/yarnpkg/berry/issues/5804), so extend its
  # pkg.json config here.
  deasync@*:
    dependencies:
      node-gyp: 'latest'