version: 2.1
orbs:
  node: circleci/node@5.1.0
  cypress: cypress-io/cypress@3.1.1
jobs:
  unit-tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
            
workflows:
    all-tests:
      jobs:
        - unit-tests
        - cypress/run:
            package-manager: yarn
            install-command: cd examples && yarn install
            start-command: cd examples && yarn start 
            cypress-command: yarn test:integration
            post-steps:
              - store_artifacts:
                  path: test/cypress/videos
              - store_artifacts:
                  path: test/cypress/screenshots