version: 2.1
orbs:
  node: circleci/node@5.1.0
  cypress: cypress-io/cypress@1
jobs:
  unit-tests:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - checkout
            - run: yarn install
            - run: yarn test
workflows:
    all-tests:
      jobs:
        - unit-tests
        - cypress/run:
            yarn: true
            start: cd examples && yarn install && yarn start
            wait-on: 'http://localhost:1234'
            command: yarn test:integration
            post-steps:
              - store_artifacts:
                  path: test/cypress/vidoes
              - store_artifacts:
                  path: test/cypress/screenshots